version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - .:/myappdocker network ls
      - /var/www/dev_ops_tutorial/shared:/var/www/cap-dp-tutorial/shared
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log

    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  bundle:
    name: bundle
  node_modules:
    name: node_modules
  public-data:
    name: public-data
  tmp-data:
    name: tmp-data
  log-data:
    name: log-data
