version: "3.9"
services:
  db:
    image: mysql:8.0
    env_file:
      - ./environments/db.env
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  mysql-data:
    driver: local
  bundle:
  node_modules:
  public-data:
  tmp-data:
  log-data:
