version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2

commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - setup
  test:
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/mysql:8-ram
        name: "db"
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: password
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test

    steps:
      - setup
      - run:
          name: apt-get update
          command: sudo apt-get update
      - run:
          name: install mysql-client
          command: sudo apt-get install default-mysql-client
      - run:
          name: rails db:create
          command: bundle exec rails db:create
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
